version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel
    container_name: simple_transfer_app

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel
    container_name: simple_transfer_web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - laravel
    container_name: simple_transfer_redis

networks:
  laravel:
    driver: bridge
